name: Run Tests with Bun

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing-job:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cache Bun’s install cache and node_modules
      - name: Cache Bun
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # 3. Configure .npmrc for GitHub Packages (si usas scopes privados)
      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "@lordcrainer:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      # 4. Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      # 5. Install dependencies with Bun
      - name: Install dependencies
        run: bun install

      # 6. Run unit tests
      - name: Run Tests
        run: bun run test
      # - name: Run unit tests
      #   env:
      #     DEBUG: 'true'
      #     SKIP_CLEAR: 'false'
      #   run: npm run test:unit

      # # Step 5: Run Integration tests
      # - name: Run Integration tests
      #   env:
      #     DEBUG: 'true'
      #     SKIP_CLEAR: 'false'
      #   run: npm run test:int

      # # Step 6: Run E2E tests
      # - name: Run E2E tests
      #   env:
      #     DEBUG: 'true'
      #     SKIP_CLEAR: 'false'
      #   run: npm run test:e2e
