name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configurate Node.js
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-deps # Identificador único para este cache
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('.releaserc') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      # Step 2.1: Configure .npmrc for GitHub Packages
      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "@lordcrainer:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      # Step 3: Set up Bun
      - name: Install dependencies
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      # Step 4: Run unit tests
      - name: Install Dependencies
        run: bun install

      # Step 4: Run unit tests
      - name: Run Tests
        run: bun run test
      # - name: Run unit tests
      #   env:
      #     DEBUG: 'true'
      #     SKIP_CLEAR: 'false'
      #   run: npm run test:unit

      # # Step 5: Run Integration tests
      # - name: Run Integration tests
      #   env:
      #     DEBUG: 'true'
      #     SKIP_CLEAR: 'false'
      #   run: npm run test:int

      # # Step 6: Run E2E tests
      # - name: Run E2E tests
      #   env:
      #     DEBUG: 'true'
      #     SKIP_CLEAR: 'false'
      #   run: npm run test:e2e
