name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Cache npm
      - name: Cache npm
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Step 3: Configure Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'

      # Step 3.1: Configure .npmrc for GitHub Packages
      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "@lordcrainer:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      # Step 4: Set up Bun
      - name: Install dependencies
        run: npm ci

      # Step 5: Run unit tests
      - name: Run Tests
        run: npm run test
      # - name: Run unit tests
      #   env:
      #     DEBUG: 'true'
      #     SKIP_CLEAR: 'false'
      #   run: npm run test:unit

      # # Step 5: Run Integration tests
      # - name: Run Integration tests
      #   env:
      #     DEBUG: 'true'
      #     SKIP_CLEAR: 'false'
      #   run: npm run test:int

      # # Step 6: Run E2E tests
      # - name: Run E2E tests
      #   env:
      #     DEBUG: 'true'
      #     SKIP_CLEAR: 'false'
      #   run: npm run test:e2e
